# Generated by Django 2.2rc1 on 2019-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='anuj', max_length=50),
            preserve_default=False,
        ),
    ]
